server {
  listen 80;
  listen [::]:80;
  server_name nuevositio.teatropigue.com.ar www.nuevositio.teatropigue.com.ar;

  # Allow Let's Encrypt verification
  location ~ /.well-known {
    root /home/teatropigue/htdocs/www.teatropigue.com.ar;
    auth_basic off;
    allow all;
  }

  # Redirect everything else to production
  location / {
    return 301 https://www.teatropigue.com.ar$request_uri;
  }
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;
  server_name www.nuevositio.teatropigue.com.ar;

  ssl_certificate /etc/letsencrypt/live/www.nuevositio.teatropigue.com.ar/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/www.nuevositio.teatropigue.com.ar/privkey.pem;

  # Redirect everything to production
  location / {
    return 301 https://www.teatropigue.com.ar$request_uri;
  }
}
