import { Router } from 'express';
import auth from './auth.js';
import users from './users.js';
import shows from './shows.js';
import sessions from './sessions.js';
import reservations from './reservations.js';
import payments from './payments.js';
import tickets from './tickets.js';
import share from './share.js';
import reports from './reports.js';
import bordereauxRouter from './bordereaux.js';
import discounts from './discounts.js';
import activityLogs from './activityLogs.js';
import notifications from './notifications.js';
import producers from './producers.js';
import cashRegister from './cashRegister.js';
import locations from './locations.js';
import admin from './admin.js';
import newsletter from './newsletter.js';
import settings from './settings.js';
import mailing from './mailing.js';
import seatBlocks from './seatBlocks.js';
import billing from './billing.js';
import ateneoRouter from './ateneo/index.js';
import sponsors from './sponsors.js';
import seo from './seo.js';
import seatPricing from './seatPricing.js';

const router = Router();

router.use('/auth', auth);
router.use('/users', users);
router.use('/shows', shows);
router.use('/sessions', sessions);
router.use('/reservations', reservations);
router.use('/payments', payments);
router.use('/tickets', tickets);
router.use('/share', share);
router.use('/reports', reports);
router.use('/bordereaux', bordereauxRouter);
router.use('/discounts', discounts);
router.use('/activity-logs', activityLogs);
router.use('/notifications', notifications);
router.use('/producers', producers);
router.use('/cash-register', cashRegister);
router.use('/locations', locations);
router.use('/admin', admin);
router.use('/newsletter', newsletter);
router.use('/settings', settings);
router.use('/mailing', mailing);
router.use('/seat-blocks', seatBlocks);
router.use('/billing', billing);
router.use('/ateneo', ateneoRouter);
router.use('/sponsors', sponsors);
router.use('/seo', seo);
router.use('/seat-pricing', seatPricing);

export default router;
